### ISSUE TITLE
can scope for canexit and canenter be made to method(&) instead of object(=)

### ISSUE THREAD

**Issue by tyagideepak** [mgonto/angular-wizard#102]
can scope for canexit and canenter be made to method(&) instead of object(=)

**Comment by jacobscarter** [comment]
+1 on this, give me a few days to implement

**Comment by jacobscarter** [comment]
+1 on this, give me a few days to implement

**Comment by jacobscarter** [comment]
@tyagideepak on second thought I think this would not be a good move.

Here is my thought behind it.  The canexit and canenter attributes take a function that is called when you try to leave or enter a certain step.  This function automatically has a context object passed into it by the Wizard that you can access and use logic to check if certain data that is required was input into a certain step.

Using the method scope type would remove our ability to inject this parameter into the function and therefor remove our ability to run logic against each step.  If you think I am mistaken or know a better way please let me know, until then I will close this issue.

Thanks.
