### ISSUE TITLE
Cannot read property 'goTo' of undefined

### ISSUE THREAD

**Issue by Ehesp** [mgonto/angular-wizard#103]
I'm trying to set which step I want to start on manually, and the docs say:

```
WizardHandler.wizard().goTo(number|title);
```

I'm using the `WizardHandler.wizard().currentStepNumber()` within functions in my controller which works, but when calling `goTo` on controller load, it gives me the error `Cannot read property 'goTo' of undefined`.

```
WizardHandler.wizard().goTo($scope.campaign.step);
```

Step is `1` in this case. Anyone know why?

**Comment by Ehesp** [comment]
Had to watch for the wizard to be initialised:

```
	$scope.$watch(function() {
		return WizardHandler.wizard();
	}, function (wizard) {
		if (wizard) {
			wizard.goTo($scope.step);
		}
	});
```

**Comment by dkushner** [comment]
I'm also encountering this issue, and while I respect the hackery of @Ehesp's solution, I don't think this is a particularly nice way of solving this. Is there some reason the wizard instance is undefined as the controller runs? That doesn't seem consistent with what happens in any of my other directives.

**Comment by firomero** [comment]
At some point in my application the solution by @Ehesp it doesn't work. Always invoking WizardHandler.wizard() if undefined crashes the application. What conditions make a null return ?
