### ISSUE TITLE
Empty context object - using controllerAs syntax

### ISSUE THREAD

**Issue by AquilaSagitta** [mgonto/angular-wizard#104]
Documentation isn't very clear on how to use or what actually gets bound to the context object.

I'm using controllerAs syntax with ng-model. The input values are being attached to the scope but the context object is still empty.

My goal is to validate that the inputs are not empty.

Edit: Also validation function (in canexit) fires twice.
Edit2: canexit function doesn't fire with wz-finish directive

**Comment by jacobscarter** [comment]
You set whatever you would like for values in the context object.  For example, lets say step 1 has an exit validation and your step two has an enter validation like so:

````
<div ng-controller="ctrl as MainCtrl">
    <wizard on-finish="finishedWizard()"> 
        <wz-step title="Starting" canexit="ctrl.exitValidation">
            <h1>This is the first step</h1>
            <p>Here you can use whatever you want. You can use other directives, binding, etc.</p>
            <input type="submit" wz-next value="Continue" />
        </wz-step>
        <wz-step title="Continuing" canenter="enterValidation">
            <h1>Continuing</h1>
            <p>You have continued here!</p>
            <input type="submit" wz-next value="Finish Now" />
        </wz-step>
</div>

//in your controller
this.exitValidation = function(){
    //where string 'John' is you can insert your ng-model the field is attached to, or anything else
    WizardHandler.wizard().context.firstName = "John";
    return true;
};
this.enterValidation = function(context){
    return context.firstName === "John";
};
```

That is a pretty stripped down example but should give you the idea.  You can set the context object at anytime you'd like `WizardHandler.wizard().context[yourKey] = yourValue` and access it at each exit or enter function via the first argument of that function.

Let me know if that makes sense.

**Comment by AquilaSagitta** [comment]
Oh I have to set it explicitly. Thought context grabbed the scope object.

**Comment by jacobscarter** [comment]
No it needs to be set explicitly, I will try and make this more clear in the documentation.

Thank you.

**Comment by AquilaSagitta** [comment]
Is there a way to bind to context directly from template?

**Comment by jacobscarter** [comment]
I would have to test in some things but you could set it equal to $scope (or this)

**Comment by AquilaSagitta** [comment]
TBH I don't really see a point to the context object since the directive isn't using an isolate scope. Its basically just another scope but with less functionality.

**Comment by jacobscarter** [comment]
It's there as an option, you don't have to use it if you prefer another method.  Thanks for your input
