### ISSUE TITLE
Loadash version upper limit

### ISSUE THREAD

**Issue by psychowico** [mgonto/angular-wizard#108]
`"lodash": ">=1.3.0 <2.5.0"`

is upper version really needed here? it looks like project work with newest version of lodash.
but I can't install it from directly from your repository cauze I use `lodash` in version 3.4.0.

**Comment by redhead** [comment]
:+1:

**Comment by jacobscarter** [comment]
This will be fixed when we remove loDash dependency, should have it up later today.

Thanks.

**Comment by fabn** [comment]
Any news on this. This is a big limit for me.

**Comment by fridjon** [comment]
This is also an issue for me. What is the reason for limiting the version of lodash to be below 2.5.0? Is there something specifically in lodash 2.5.0 that would break things?

**Comment by psychowico** [comment]
@jacobscarter this limit is still there.

**Comment by jacobscarter** [comment]
@psychowico I have it scheduled for next release that will be done by Jan 1 2016.

**Comment by jacobscarter** [comment]
See #116

**Comment by jacobscarter** [comment]
This had been removed and will be in the 0.6.0 release
