### ISSUE TITLE
canexit not working with controllerAs

### ISSUE THREAD

**Issue by corneadoug** [mgonto/angular-wizard#114]
Hi,

I've been trying to use ``canexit`` using controllerAs but it never reached the function.

``ng-controller="myCtrl"`` and ``canexit=verify`` works
``ng-controller="myCtrl as wootCtrl"`` and ``canexit=wootCtrl.verify`` doesn't work :(

**Comment by jacobscarter** [comment]
@corneadoug  Can you create a fiddle?

**Comment by corneadoug** [comment]
Sure, I will do

**Comment by corneadoug** [comment]
I just successfully used it, I guess I was doing something wrong in my controller (not using this.functionName maybe)

**Comment by jacobscarter** [comment]
glad you got it resolved
