### ISSUE TITLE
Error using goTo

### ISSUE THREAD

**Issue by narangrishab** [mgonto/angular-wizard#115]
TypeError: Cannot read property 'canenter' of undefined
    at Scope.a.goTo (assets/plugins/angular-wizard/angular-wizard.min.js:7)

When I click on the Tabs, it shows error.

**Comment by jacobscarter** [comment]
@narangrishab  Can you create a fiddle?

**Comment by narangrishab** [comment]
'use strict';

/* Controllers */

angular.module('app', ['mgo-angular-wizard'])
    .controller('FormWizardCtrl', ['$scope', 'WizardHandler', function($scope,WizardHandler) {

         $scope.finished = function() {
            alert("Wizard finished :)");
        }

        $scope.logStep = function() {
            console.log("Step continued");
        }

        $scope.goBack = function() {
            WizardHandler.wizard().goTo(0);
        }

        $scope.getCurrentStep = function(){
            return WizardHandler.wizard().currentStepNumber();
        }
        $scope.goToStep = function(step){
            WizardHandler.wizard().goTo(step);
        }

    }]);

That's my Angular JS code for form wizard. Would this work? or do you want a fiddle in specific?

**Comment by jacobscarter** [comment]
@narangrishab Can you make a fiddle so I can play around with it? I think I see the issue but I would know for sure if I could click around.

**Comment by Adverse191** [comment]
```javascript
this.goTo = function(step) { 
                var enabledSteps = $scope.getEnabledSteps();
                var stepTo;
                //checking that step is a Number
                if (_.isNumber(step)) {
                    stepTo = enabledSteps[step]; ...
```

According to this code `goTo` uses only enabled steps. This was issue in my case.

**Comment by createthis** [comment]
I think this happens when using title instead of wz-title. Someone needs to update the documentation. It still says title in places.

**Comment by jacobscarter** [comment]
@createthis @Adverse191 @narangrishab This issue has been fixed with the latest release.
