### ISSUE TITLE
wz-next, wz-previous and wz-finish outside wizard forms

### ISSUE THREAD

**Issue by xvitcoder** [mgonto/angular-wizard#122]
It would be nice to have the next, previous and finish buttons outside the wizard forms. For example when using this wizard in the Bootstrap Modal Dialog, the buttons must be in different DOM tree level.

**Comment by jacobscarter** [comment]
@xvitcoder can you give me an example here? Perhaps put up a CodePen or something.

I use the wizard in Bootstrap Modals all the time and have not had an issue with the next and previous buttons, Keep in mind that you do not have to use the modal footer, you can put everything in the modal body section and mimic the look of a footer with CSS.

You also have access to the next and previous command via ` WizardHandler.wizard().next();` and so forth.  You could use this to place your next and previous buttons outside of the step HTML

**Comment by jacobscarter** [comment]
@xvitcoder does that answer your questions? I am marking this ticket to be closed unless you have further questions

**Comment by xvitcoder** [comment]
Yes, all is clear now
