### ISSUE TITLE
By default the wizard UI is displayed at the bottom, is it possible to move it to the top ?

### ISSUE THREAD

**Issue by shayhz** [mgonto/angular-wizard#123]

**Comment by jacobscarter** [comment]
Hi @shayhz, if we move the wizard to the top by default some will want it on the bottom and vice versa.  So we will just leave it where it is.  You can move it to the top with custom css to overwrite the default.  Here is an example of what that would look like:

    .steps-indicator {
      top: 0;
      position: absolute;
      ......
    }

**Comment by odyright** [comment]
Great
