### ISSUE TITLE
Cannot read property 'title' of undefined when adding model to current-step attribute

### ISSUE THREAD

**Issue by TheBekker** [mgonto/angular-wizard#130]
Im generating my wizard with ng-repeat over a model like this quick example

Code:

    function FormEcController(is, WizardHandler) {
        var vm = this;

        vm.wizard = {
            formWiz: {},
            currentStep: {}
        }
    
        vm.model = {};
        vm.options = {};
        vm.steps = new Array();

        var step1 = {
            title: "step title",
            header: "Header text",
            inputs: [{
                ...
            }]
        };
        var step2 = {
            title: "step title",
            header: "Header text",
            inputs: [{
                ...
            }]
        };
        vm.steps.push(step1, step2);
        ...
    };

Markup:

    <wizard on-finish="vm.finished()" name="vm.wizard.formWiz" current-step="vm.wizard.currentStep">
        <wz-step title="{{step.title}}" ng-repeat="step in vm.steps" wz-disabled="step.hideExpression()}}">
            ...
        </wz-step>
    </wizard>

The above code has been working fine, but since i now need to track the current step, i added the "current-step" attribute to the wizard directive. and now it throws this error in console:

    TypeError: Cannot read property 'title' of undefined

My js is bundled, but it happens at line 40 in wizard.js

If i remove it, then everything is fine. not sure if it has somthing to do with the steps being generated with ng-repeat?

**Comment by jacobscarter** [comment]
Hey @TheBekker I have a few questions.  Was the wz-disabled there before it threw errors? Is the code `wz-disabled="step.hideExpression()}}"` like that in your code or did you just type it wrong (there are two }} at the end of the expression)?

In regards to the `name` attribute.  This attribute is attached to the directive scope via `@` which is a one way or read only binding.  This means you will need to write an angular expression for the `name` attributes value.  It would look like this `name="{{vm.wizard.formWiz}}"`.  Also the directive is looking for a string here, not an object.  So you would want to change your controller to look like this:

```
vm.wizard = {
    formWiz: "MyWizardTitle",
    currentStep: {}
}
```

Your current step can be set as an object in your controller but it will be overwritten with a string as soon as the wizard loads with a string (the step title).  So I would suggest setting it to `undefined` on declaration rather then an empty object.

Also keep in mind if you change your wizard name you will need to add that name when using the `WizardHandler` service.  It would look like this using my example above:

```
Wizard.Handler.wizard('MyWizardTitle').<methodHere()>
```

I would suggest cleaning those things up and then seeing if you still get your error.

Thanks.

**Comment by TheBekker** [comment]
Hi 

The wz-disable was just a type here.
I just tested without defining the currentStep as object (tried as undefined and as string), and that fixed. Apparently it doesn't overwrite it on load, if its defined as object?

But that helped, thanks!

**Comment by jacobscarter** [comment]
No problemo
