### ISSUE TITLE
Get the number of steps

### ISSUE THREAD

**Issue by maseev** [mgonto/angular-wizard#132]
Hi there! I've noticed that angular-wizard API lacks of a function that can return the number of steps. It would be very helpful for those who develop their custom components that are using your angular directive. For example, I've run into the problem recently when I don't know how many steps there would be, because it (the number of steps) depends on what options a user would choose.

**Comment by jacobscarter** [comment]
This can be added, with the enable disable feature it will probably be get the number of enabled steps

**Comment by jacobscarter** [comment]
This has been added and will be in next push
