### ISSUE TITLE
how to extend wzStep directive?

### ISSUE THREAD

**Issue by cmnstmntmn** [mgonto/angular-wizard#135]
i wand to add the **step-description** as an attribute to  [wzStep](https://github.com/mgonto/angular-wizard/blob/master/src/step.js) directive

```html
<wz-step title="Step title" description="step description">
...
```

i try using a decorator .. but i don't know about configurator provider for this directive ..

```js
    $provide.decorator('wzStep', ['$delegate', function ($delegate) {
              angular.extend($delegate[0].scope, {
                  description: "="
              });
        return $delegate;
    }]);  
```

but it doesn't work

**Comment by jacobscarter** [comment]
Hey @cmnstmntmn I have little experience with using decorators in Angular 1.x, my understanding is that you can use them to monkeypatch Services, I am not familiar with using them to alter Directives, I could be wrong.  I know that when you create a Directive it creates a Provider for it, but I dont know if you can decorate that or not, Sorry I dont know how much help I can be.  I would just change the source code and make a proposal to have it added to the repo.

Hope that helps

**Comment by cmnstmntmn** [comment]
```js
.config(function (NgAdminConfigurationProvider,  $provide) {        
      $provide.decorator('wzStepDirective', function($delegate) {
            var directive = $delegate[0];

            directive.$$isolateBindings['description'] = {
              attrName: 'description',
              mode: '@',
              optional: true
            };

            return $delegate;
         });
});
```

it worked

**Comment by jacobscarter** [comment]
This has been added and will be included in the next push
