### ISSUE TITLE
edit-mode directive is only one way binding

### ISSUE THREAD

**Issue by franciscopuyo** [mgonto/angular-wizard#138]
Hi, I am creating a wizard for edition and creation. And depending of what the user is doing I should set if it is in edit mode or not.

The fact is the attribute edit-mode is only one way bound so if I first create an entity it starts with editMode set on false, but if after it I want to edit another entity, editMode can't change to true.

I've tried with edit-mode="{{editMode}}" but it doesn't work as I expected.

Thanks

**Comment by jacobscarter** [comment]
Can you elaborate on this example or provide a code example.  I'm not sure I know what you are getting at.

**Comment by jacobscarter** [comment]
@franciscopuyo I found a problem that only allowed edit mode to be toggle once, I corrected it and it will be in the next push.

```html
<button ng-click="clickToggle()">Toggle Edit Mode</button>
<wizard on-finish="finishedWizard()" hide-indicators="false" edit-mode="editToggle">
...
```
```javascript
$scope.clickToggle = function() {
    $scope.editToggle = !$scope.editToggle;
};
```

This will work

**Comment by mindscratch** [comment]
My use case is like so:
* bind `edit-mode` to a variable in my component: `edit-mode=$ctrl.wizardEditMode`
* initially wizardEditMode is false
* a user selects an item from a list, wizardEditMode gets set to true.

Things work so far. Then when the user is done performing their task, they hit a save button and I "reset" the wizard. After resetting, changes to the `wizardEditMode` variable, aren't being picked up by the $watch on `editMode` in the angular-wizard source. I'd like the editMode logic to be in a function so I can invoke it.

I'll submit a pull request in a moment.

**Comment by mindscratch** [comment]
Pull request added: https://github.com/angular-wizard/angular-wizard/pull/236
