### ISSUE TITLE
How to know in which step I wanna enter

### ISSUE THREAD

**Issue by franciscopuyo** [mgonto/angular-wizard#139]
I'm trying to do the following:
A list of steps with one form on each. The fact is my canenter function should validate if all previous forms are valid to the step i want to enter, not only the current one.
PD: I'm handling forms status in an array ($scope.validSteps = [true, true, false, ... )

**Comment by jacobscarter** [comment]
you write your own `canenter` function that returns true or false letting someone move to the next step.  If you want to check previous steps before allowing someone through, then do that.  You can access the other steps data via your controllers scope or using the context object available to you.

https://github.com/mgonto/angular-wizard#wizard-step-validation
