### ISSUE TITLE
adding reset

### ISSUE THREAD

**Issue by joshting** [mgonto/angular-wizard#142]
Hi all,
I have never contributed to the open source repository.  When using angular-wizard, I found that cancelling does not clear "completed" steps.  Therefore, I need to add a reset function:

            //reset
            this.reset = function(){
                //traverse steps array and set each "completed" property to false
                _.each($scope.getEnabledSteps(), function (step) {
                    step.completed = false;
                });
                //go to first step
                this.goTo(0);
            }

This is useful when the wizard needs to be repeated to populate the same set of data.
How can I add this to the repository... or someone can add for me?

**Comment by tymat** [comment]
+1

**Comment by WaitWut** [comment]
+1

Thanks joshting

**Comment by jacobscarter** [comment]
I can add this feature, note that we cannot clear out your models you use within the wizard but we can change step completion statuses

**Comment by jacobscarter** [comment]
This is added and will be in the next push
