### ISSUE TITLE
errror in template loading

### ISSUE THREAD

**Issue by amirkheirabadi** [mgonto/angular-wizard#143]
when i try use mgo-angular-wizard this return error me ....

ET http://.../wizard.html 404 (Not Found) 
ET http://.../step.html 404 (Not Found) 

how i can disable external view and use internal view for this .????

**Comment by jacobscarter** [comment]
The `<wizard></wizard>` directive takes a template attr.

`<wizard template="path/to/temp.html"></wizard>`
