### ISSUE TITLE
canexit called twice when returning boolean

### ISSUE THREAD

**Issue by vketsenko** [mgonto/angular-wizard#145]
If canexit function returns true\false, it is always called twice.
Reason: bug in wizard.js, line 168
`return step.canexit($scope.context) === true;`
should be replaced with
`return canExit  === true;`
because step.canexit has already been called on line 160

**Comment by ElielHaouzi** [comment]
+1

**Comment by bradleybossard** [comment]
+1 I would like to call a toastr nofication in this function if the step does validate, but current it keeps getting fired twice.

**Comment by vketsenko** [comment]
bradleybossard, as temporar solution you may return promise instead of boolean. It works correctly with promises.
`return $q.when([]);`

**Comment by jacobscarter** [comment]
Looking into this, want to make sure fixing the double call doesn't break other functionality.

**Comment by jwuliger** [comment]
I spent hours wondering what was going on before I say this post. @vketsenko thanks for the tip! For anyone who wants a working work-around here is my exitValidation function when dealing with form input.

```javascript
function exitValidation() {
	var d = $q.defer();
	$timeout(function() {
		if (vm.myForm.$invalid) {
			logger.error("Please enter a title"); // Shows toast
			return d.resolve(false);
		} else {
			return d.resolve(true);
		}
	}, 100);
	return d.promise;
};
```

**Comment by jacobscarter** [comment]
corrected and in next release
