### ISSUE TITLE
What if i want the step of each page on the bottom?

### ISSUE THREAD

**Issue by aaronucsd** [mgonto/angular-wizard#149]
<img width="324" alt="screen shot 2015-12-13 at 12 36 02 am" src="https://cloud.githubusercontent.com/assets/8840761/11766201/96d122ac-a131-11e5-8a19-0f2a31fadfa3.png">

**Comment by jacobscarter** [comment]
You can change the styles by over writing them in your own custom css file. But I'm not sure what you mean because the steps are at the bottom by default.

**Comment by aaronucsd** [comment]
NOt the steps like 'welcome', but see the content 'Hello John'. I want the content to be below the wizard steps. Right now, your demo shows the content and buttons on top of the wizard steps. How to swap the content to below?

**Comment by aaronucsd** [comment]
How to move the div with the class 'steps' to be below the ul with class 'steps-indicators'?

**Comment by aaronucsd** [comment]
Only way for it to work with css is like so. I was wondering if there is a more programatic way through a predefined attribute.
