### ISSUE TITLE
Specify current-step is used in conjunction with wz-title

### ISSUE THREAD

**Issue by guikubivan** [mgonto/angular-wizard#157]
I spent a long time trying to figure how to update the current-step and I thought I could use the title attribute in wz-step, but finally figured out I have to use wz-title (by looking at the code). It would be handy to say this in the documentation.

**Comment by Deepindera** [comment]
@guikubivan 
How did you use the current-step. for me it is always null or '' or whetever i set it initially in scope

**Comment by jacobscarter** [comment]
CHANGELOG will be added

**Comment by guikubivan** [comment]
Thank you!
