### ISSUE TITLE
[BUG] titles do not  appear under step anymore in 1.6

### ISSUE THREAD

**Issue by jmorvan** [mgonto/angular-wizard#159]
Using latest CDN i recently had a bug where no labels would show under the steps. 

manually switching to 1.5 solved it. 

Seems like something broke in that area in the last release.

**Comment by ssuhat** [comment]
+ 1 experiencing this issue

**Comment by appernetic** [comment]
Just recognized that the labels was gone. Could not find any local error in my code. What could have changed? 
Heavy backend development. Don't have time with front end cosmetics right now, so switching to 1.5.

**Comment by tbloncar** [comment]
One way around this is to provide a wizard template that leverages the `description` property (rather than `title`). Something like this should work.

Template:
```html
<div>
  <div class="steps" ng-transclude></div>
  <ul class="steps-indicator steps-{{getEnabledSteps().length}}" ng-if="!hideIndicators">
    <li ng-class="{default: !step.completed && !step.selected, current: step.selected && !step.completed, done: step.completed && !step.selected, editing: step.selected && step.completed}" ng-repeat="step in getEnabledSteps()">
      <a ng-click="goTo(step)">{{step.description}}</a>
    </li>
  </ul>
</div>
```

Wizard markup:

```html
<wizard on-finish="finishedWizard()" template="path/to/template.html"> 
  <wz-step title="starting" description="Starting">
    <h1>This is the first step</h1>
    <p>Here you can use whatever you want.</p>
    <input type="submit" wz-next value="Continue" />
  </wz-step>
  <wz-step title="continuing" description="Continuing">
    <h1>Continuing</h1>
    <p>You have continued here!</p>
    <input type="submit" wz-next value="Go on" />
  </wz-step>
</wizard>
```

**Comment by cristianstanescu** [comment]
It seems that specifying a title with either `title` or `wz-title` was removed and only `wz-title` kept since: https://github.com/mgonto/angular-wizard/commit/b37185f904506f0f5e7685db886466b826248c74#diff-218e72699d8aeae3725da9dcae6bd08dR47

I've replaced `title` with `wz-title` in the `wz-step` definition and also used just

    a[ng-click="goTo(step)"] {{step.wzTitle}}

instead of

    a[ng-click="goTo(step)"] {{step.title || step.wzTitle}}

in my custom `wizard.html` and everything back to normal.

**Comment by diego-vieira** [comment]
was struggling to find out why it broke after the update and no notice about breaking changes.
README still shows title instead of wz-title.

**Comment by esoyke** [comment]
+1 Not a big deal for me to change title to wz-title, but the README should at least be made consistent, as diego-vieira pointed out. The code example shows title, yet the explanation below shows wz-title, which clued me to the fix.

**Comment by jacobscarter** [comment]
A CHANGELOG needs to be implemented, sorry for the confusion, making an issue as a reminder to implement a CHANGELOG and update README
