### ISSUE TITLE
(building tools) stop grunt from including css file

### ISSUE THREAD

**Issue by Frondor** [mgonto/angular-wizard#162]
I certainly don't want to include `angular-wizard.min.css` file on my document, simply because I'm fully overriding it on my `main.css` file. 
![](https://i.gyazo.com/08bc7330332fa58ff68ca20098417720.png);
 
So at the moment, I'm overriding `bower.js` just like  

      "overrides": {
        "bootstrap": {
          "main": [
            "less/bootstrap.less",
            "dist/css/bootstrap.css",
            "dist/js/bootstrap.js"
          ]
        },
        "angular-wizard": {
          "main": [
            "./dist/angular-wizard.min.js"
          ]
        }
      }

In this case I think you should consider making `angular-wizard.min.css` file an optional file, because it is not really necessary. Most people would like to create its own template, and the one who doesn't simply add it manually.

This is not an issue at all, but rather a suggestion :+1: 
Thanks for such nice directive.

**Comment by jacobscarter** [comment]
Roger that, I haven't gotten any other request for an optional CSS but I will add it to the discussion to see if there is a need for this by other people.  Thanks for the comment! :)
