### ISSUE TITLE
goTo with step name isn't working

### ISSUE THREAD

**Issue by glaidler** [mgonto/angular-wizard#163]
Hi,

I have created a basic wizard, which I need to navigate via code.  When I try to execute WizardHandler.wizard().goTo('stepName'), I get 

 Cannot read property 'canenter' of null
    at f (angular-wizard.min.js:7)
    at Scope.a.goTo (angular-wizard.min.js:7)

The step name is definitely correct, and if I use the index param rather than step name it works fine.

I'm using 0.6.1

**Comment by nmiddendorff** [comment]
I had the same issue. At some point they changed directive property from title to wz-title. 

<wz-step wz-title="Step1">

Use wz-title and .goTo() should work fine.

**Comment by moneytree-doug** [comment]
@nmiddendorff Wow, I really wish there was a changelog. Thanks for documenting this. I was digging deep into the library to figure out what's wrong.

**Comment by jacobscarter** [comment]
Yes a CHANGELOG is badly needed, I have an issue up to add one, sorry for the confusion.
