### ISSUE TITLE
Can't get wz-next="setMode(mode)" to work

### ISSUE THREAD

**Issue by yzaroui** [mgonto/angular-wizard#171]
In a step, I put `wz-next="setMode(mode)"`, but where this setMode function must be?

**Comment by ashthespy** [comment]
Any points as to how you solved this? 
Having similar issues (angular wizard + formly)

**Comment by jacobscarter** [comment]
@ashthespy @yzaroui You setMode() function would be in the controller wrapping your wizard.

**Comment by ashthespy** [comment]
I had a silly error attributed to rudimentary JavaScript skills, can mark this as closed.
