### ISSUE TITLE
wizard() is undefined in Angular 1.5.0

### ISSUE THREAD

**Issue by moneytree-doug** [mgonto/angular-wizard#173]
Here is an example of it working in Angular 1.4.7 and an example of it breaking in 1.5.0:

1.4.7: http://plnkr.co/edit/7ZPBgqpPnbXF57rvezPf?p=preview
1.5.0: http://plnkr.co/edit/5Nh7EHLINDjMlaQ8dZbl

I `console.log`ed the results.

**Comment by moneytree-doug** [comment]
Upon closer inspection, I believe this is an Angular "bug". I reported here: https://github.com/angular/angular.js/issues/14343

**Comment by jacobscarter** [comment]
Okay thank you @moneytree-doug I will close the issue since you've logged it on Angular's page

**Comment by vbarinov** [comment]
Any workaround for this, guys? I need a `wizard` instance in my controllers :)

**Comment by moneytree-doug** [comment]
@vbarinov Look at the post in Angular that I linked

**Comment by vbarinov** [comment]
@moneytree-doug yeah, I used `^^` example, but with no luck. `WizardHandler` are injecting in constructor,  hence, by the time helper directive calls `onInit` it havent wizard instance with proper scope.

**Comment by Zemke** [comment]
It’s also worth to note that there might just be a delay, so you’d need to wait for some digest cycles to have run until there’s your wizard returned by `WizardHanderl.wizard()`.

Example component in TypeScript running `$doCheck` on every digest cycle until the wizard is found:

```typescript
/// <reference path="../../../../../rest.d.ts"/>
/// <reference path="../../../../../typings/index.d.ts"/>

module App {

    class UploadWizardComponentCtrl implements ng.IController {
        public readonly WIZARD_NAME = 'Manual product upload';
        public wizard: angular.mgoAngularWizard.Wizard;

        constructor(private $location: ng.ILocationService, private WizardHandler: angular.mgoAngularWizard.WizardHandler) {
        }

        $doCheck(): void {
            if (this.wizard) {
                return;
            }

            let wizard: angular.mgoAngularWizard.Wizard = this.WizardHandler.wizard(this.WIZARD_NAME);

            if (wizard) {
                this.wizard = wizard;
            }
        }

        public cancel(): void {
            this.$location.path('/uploads');
        }
    }

    UploadWizardComponentCtrl.$inject = ['$location', 'WizardHandler'];

    angular
        .module('app')
        .component('pkpUploadWizard', {
            controller: UploadWizardComponentCtrl,
            templateUrl: 'app/upload-wizard/upload-wizard.component.html',
            bindings: {}
        });
}

```
