### ISSUE TITLE
Syntax to dynamically disable a step other than current step

### ISSUE THREAD

**Issue by chrisrgreen** [mgonto/angular-wizard#175]
According to the guidance, the syntax to disable the current step is
 $scope.disabled = 'true';

But what is the syntax to disable a step other than the current step? I have looked through the documentation, issues and code and cannot work it out - am I missing something obvious? 

Based on previous answers in the current step, I wish to disable/enable later steps, before going to the next step (which may be now disabled). Based on reading #42 this is now possible.

**Comment by jacobscarter** [comment]
each step can take a disabled attribute and each one can references a different value in your controller, e.g.

```
$scope.disableStep1 = true;
$scope.disableStep2 = true;
```

etc.
