### ISSUE TITLE
How to call function after go to next step

### ISSUE THREAD

**Issue by essivision** [mgonto/angular-wizard#176]
Hi
I want to call a function after go to next step. In this function I use WizardHandler service to go last step  but won't work. It's my code:

```
<wizard on-finish="finishedWizard()">   
    <wz-step wz-title="Mapping" >
        <div class="form-group">                        
            <div class="col-sm-9">
                <select ng-model="mapForm[value]" ng-options='column as column for column in columns' class="form-control"></select>
            </div>
        </div>                   
        <div class="col-xs-4 col-xs-offset-4">
            <button type="button" class="btn btn-block btn-primary" wz-next="importSubmit()">Next: Import Data</button>
        </div>
    </wz-step>
    <wz-step wz-title="Process">
        <div class="text-center">
            <h3 class="bold">Please Wait...</h3>
            <p>It may take a few minutes</p>
        </div>
    </wz-step>
    <wz-step wz-title="result">
        <h3 class="text-center">Import Result</h3>
        <div class="col-xs-4 col-xs-offset-4 well">
            Finish
        </div>
    </wz-step>
</wizard>
```

and in controller:
```
$scope.importSubmit = function(){
        WizardHandler.wizard().goTo(2);
    };
```

**Comment by jacobscarter** [comment]
Can you provide me with more details? What behavior are you getting? Right now with the code the way you have it, the function that is called on importSubmit does the exact same thing clicking wz-next in your partial does.  What results are you wanting?

**Comment by essivision** [comment]
I solved problem with this:

1. remove `wz-next` attribute
2. add `ng-click="importSubmit()"`.
3. add this code in controller
```
    $scope.importSubmit = function(){
        WizardHandler.wizard().next();
    }
```

**Comment by jacobscarter** [comment]
Okay glad you found a solution, just for your knowledge you can add the wz-next attribute with no method inside, e.g. `<button wz-next>next</button>` and it will perform the same operation as your ng-click.
