### ISSUE TITLE
functionality similar to onEnter (after step DOM is rendered)

### ISSUE THREAD

**Issue by pliablepixels** [mgonto/angular-wizard#178]
Hi there, thanks for this lovely library.

Is there a good way to implement a functionality that calls a controller function right after a step is entered? As of today we have ``wz-next="function()"`` that executes function() _before_ the next step is reached. I am looking at a means to execute a function _after_ the next step is loaded because I need to display some values in the step's HTML template (Which is loaded via http and takes time, and I want to initiate the http call only after entering the step)

thanks

**Comment by pliablepixels** [comment]
Closing - I achieved what I needed by replacing wz-next of the previous step with ng-click and using the WizardHandler to programmatically do a wizard.next() (which loads the DOM) and then invoke my on enter function. Thanks!

**Comment by jacobscarter** [comment]
@pliablepixels glad you found a solution!
