### ISSUE TITLE
How to get content of a step at the bottom of Navigation bar

### ISSUE THREAD

**Issue by gclouds** [mgonto/angular-wizard#202]

**Comment by jacobscarter** [comment]
Not sure I understand the question fully, but I think you are referring to the indicators-position attribute, see instructions on use in the [README.md](https://github.com/mgonto/angular-wizard/blob/master/README.md)

**Comment by gclouds** [comment]
thanks I meant the same :+1:

**Comment by gclouds** [comment]
but indicators-position="top" is not working, still I am not getting the navigation strip at bottom

**Comment by gclouds** [comment]
@jacobscarter please help me

PFA code

_> 
> 
> <wizard on-finish="finishedWizard()" indicators-position="top"> 
> 	
> 	<wz-step wz-title="BASICS"> <md-content class="md-padding">
> 
> 	</wz-step> <wz-step wz-title="TEST DATA"> <input
> 		class="btn btn-success" type="submit" wz-next value="Go on" />
> 
> 
> 	<h1>Continuing</h1>
> 	<p>You have continued here!</p>
> 	</wz-step> <wz-step wz-title="VALIDATIONS"> <input type="submit"
> 		wz-next value="Finish now" />
> 
> 	<p>Even more steps!!</p>
> 
> 	</wz-step> <wz-step wz-title="RESPONSE"> <input class="btn btn-success"
> 		type="submit" wz-next value="Finish now" />
> 
> 	<p>Even more steps!!</p>
> 	</wz-step> </wizard>
> 
>_

**Comment by jacobscarter** [comment]
I don't see your opening `<wizard>` tag in your example
