### ISSUE TITLE
Styling Issues with navigation line

### ISSUE THREAD

**Issue by kentcdodds** [mgonto/angular-wizard#34]
See screenshot:

![Styling issues with angular-wizard navigation line](http://cl.ly/image/362w3p2W0B00/Image%202014-05-30%20at%208.44.48%20AM.png) 

If that's not showing for some reason, [click here](http://cl.ly/image/362w3p2W0B00) to see it.

I've tried to show all the css from the dev tools. Let me know what more information I can give you...

**Comment by mgonto** [comment]
@jacobscarter can you check this one if you have time? @kentcdodds is using it with Angular Formly, and it'd be lovely to fix it. 

Otherwise, I'll check it out next week :).

Thanks everyone for all the help in finding the issue!

**Comment by kentcdodds** [comment]
Here's the working example: http://angular-formly.com/#/example/other/angular-wizard

**Comment by mgonto** [comment]
So the fix is changing from `recess` to `grunt-contrib-less`.

Sounds good

**Comment by jacobscarter** [comment]
@mgonto about to push the fix and update the package

**Comment by mgonto** [comment]
Great work @jacobscarter :). Thanks!

@kentcdodds can you update the sample for Angular-formly?

Cheers!
