### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by kylejeske** [mgonto/angular-wizard#35]
when using this as an include through bower install angular-wizard and then doing an include of dist/angular-wizard.min.js -- it will throw an error about _ not being defined.

I included lodash.underscore.min.js (from another library) to fix this, I notice it says lodash is a dependency in the README file.

But perhaps you can make this more clear in the README that you are going to need to include both lodash & the core files?

**Comment by 2wings** [comment]
it works~!require('lodash.underscore')

**Comment by jacobscarter** [comment]
The issua of lodash has been brought up several times, I plan on removing the dependency in the next push
