### ISSUE TITLE
Animations with NGAnimate?

### ISSUE THREAD

**Issue by cranesandcaff** [mgonto/angular-wizard#4]
I'm sorry, I didn't see in the documentation, does this support animation with ng-animate? If so, what is the syntax?

**Comment by YidingW** [comment]
Is there any wan to animate the steps navigation? For example, fade-in when first load?

**Comment by nomoreboredom** [comment]
This does the trick:
.step.ng-hide {
    opacity: 0;  
}
.step.current {
    opacity: 1;
	transition: all 1s ease-in-out;
}
