### ISSUE TITLE
How to change the position of navigation bar?

### ISSUE THREAD

**Issue by bpbhat77** [mgonto/angular-wizard#40]
How to add navigation bar at top?
or left/right/top/bottom
is there any configuration/flag?

**Comment by LennyLip** [comment]
i think, css is not enough for this. With css "placement" we need also "target" to set position the bar relative to a specific target element (like in a angular-strap). What about if i want nav bar, that not fixed and relative to a specific target element?

**Comment by YidingW** [comment]
For chaning it to top. I don't think css fixed is the solution. 

Solution: 

Inside angular-wizard.js file, move **\<ul> html** from bottom to above of **div with class "steps"**. So the steps nav will generate before the steps section. So steps nav will show on top of the steps section.

**Comment by geostima** [comment]
for most purposes editing the angular-wizard.js file will do the trick, but for some projects where deployment are done using bower and the like, this file is automatically downloaded and decoupling it from the project just to have this is too hacky. I had an instance of this exact issue. My solution was quite simple. CSS. It was more than enough to get everything working as it should and have the navigation steps above the wizard - fully angular - fully bootstrapped and fully response, no issue on any browser.

**Comment by libin85** [comment]
How do i move the navigation bar to a separate div? I want the navigation var to be on a separate div that will be on the right hand side of the wizard.

**Comment by jacobscarter** [comment]
You can use custom css to overwrite or you can change the source files once you download.  With all the different possible ways people may want the HTML and CSS done we can accommodate them all :( We do try to make it easy to make changes though

**Comment by b-t-o** [comment]
@geostima editing like this, won't work for me:

`  $templateCache.put("wizard.html",
    "<div>\n" +
    "    <ul class=\"steps-indicator steps-{{getEnabledSteps().length}}\" ng-if=\"!hideIndicators\">\n" +
    "      <li ng-class=\"{default: !step.completed && !step.selected, current: step.selected && !step.completed, done: step.completed && !step.selected, editing: step.selected && step.completed}\" ng-repeat=\"step in getEnabledSteps()\">\n" +
    "        <a ng-click=\"goTo(step)\">{{step.title || step.wzTitle}}</a>\n" +
    "      </li>\n" +
    "    </ul>\n" +
    "    <div class=\"steps\" ng-transclude></div>\n" +
    "</div>\n" +
    "");
`

The nav bar is above as expected - but the active section has now no width and isn't displayed anymore.

Tested with this example:
`<wizard on-finish="finishedWizard()"> 
    <wz-step wz-title="Starting">
        <h1>This is the first step</h1>
        <p>Here you can use whatever you want. You can use other directives, binding, etc.</p>
        <input type="submit" wz-next value="Continue" />
    </wz-step>
    <wz-step wz-title="Continuing">
        <h1>Continuing</h1>
        <p>You have continued here!</p>
        <input type="submit" wz-next value="Go on" />
    </wz-step>
    <wz-step wz-title="More steps">
        <p>Even more steps!!</p>
        <input type="submit" wz-next value="Finish now" />
    </wz-step>
</wizard>`
