### ISSUE TITLE
Step validation?!

### ISSUE THREAD

**Issue by schmitch** [mgonto/angular-wizard#41]
Currently maybe It's just missing the documentation part, but is there an easy way to validate all the steps? 
Currently we previously used https://github.com/VinceG/twitter-bootstrap-wizard but since that wizard isn't 'that' good we will change to the one you provide. But we need an easy way to validate all ours steps.
there should be a handler where we could inject a a function like `_validate_steps()`.

Is this possible at all?

Edit:
I found out a way.
I just patched $scope.goTo = funcion(step) where it has an if like that:

```
$scope.goTo = function(step) {
                    var index = _.indexOf($scope.steps , step);
                    if (self._validate_step(step) || index == 0) {
                        unselectAll();
                        $scope.selectedStep = step;
                        if (!_.isUndefined($scope.currentStep)) {
                            $scope.currentStep = step.title || step.evTitle;
                        }
                        step.selected = true;
                        $scope.$emit('wizard:stepChanged', {step: step, index: index});
                    }
                };
```

now i've also added the _validate_step function:

```
                self._validate_step = function(step) {
                    var handler = WizardHandler.getValidation($scope.name || WizardHandler.defaultName);
                    var result = _.reduce(handler, function(result, fn) {
                        var ret = fn(step);
                        return result && (angular.isDefined(ret) ? ret : true);
                    }, true);
                    console.log(result);
                    return result
                }
```

and added two helper functions to the Handler:

```
       var _validation_methods = {}

       service.addValidation = function(name, fn) {
            var nameToUse = name;
            if(!fn) {
                nameToUse = service.defaultName;
                fn = name;
            }
            if (!_validation_methods.nameToUse) {
                _validation_methods[nameToUse] = [];
            }
            _validation_methods[nameToUse].push(fn);
       };

       service.getValidation = function(name) {
            var nameToUse = name;
            if(!name) {
                nameToUse = service.defaultName;
            }
            return _validation_methods[nameToUse];
       }
```

now you could add validation functions to the wizard as you want.

Edit2: Also it would be great that you change the license to the Apache License since I would contribute a patched version to your code to the Openstack Project and its way better to contribute APL2 Code instead of MIT Code (MIT is not permitted but the Rest of the Project ist mostly APL2)

**Comment by nishithchaturvedi** [comment]
Is the latest version availlble?
