### ISSUE TITLE
Dynamic Steps in a Wizard

### ISSUE THREAD

**Issue by sushil-vishwanathan** [mgonto/angular-wizard#42]
Hi:
I would like to implement a wizard which would have dynamic steps, meaning a model value from one step would decide whether or not subsequent steps are required. How do I achieve this with the current version of angular-wizard?
Thanks in advance

**Comment by donnguyen** [comment]
@jacobscarter I think there still is someone here waiting for your solution! ;)

**Comment by jacobscarter** [comment]
you can now enable and disable steps dyanmically

**Comment by gino8080** [comment]
is it possible to make a disabled step VISIBLE but NOT selectable?

I want the disabled step to remain in the step list in the navigation, BUT no selectable, 

so if I have 4 steps
and the 3rd is disabled

i'll see all 4 steps on navigation bar
when i complete the 2nd I'll go directly to the 4th

hope i explained :)

thank you

**Comment by gino8080** [comment]
Anyone?

**Comment by jacobscarter** [comment]
We could implement this feature, would you be willing to create a PR with this new functionality?
