### ISSUE TITLE
Standard NuGet package

### ISSUE THREAD

**Issue by dsaf** [mgonto/angular-wizard#61]
Hi,

Would it be possible to have it released as a standard package (NuGet)?

Thanks!

**Comment by HarelM** [comment]
+1

**Comment by jstensved** [comment]
Microsoft is moving away from Nuget towards npm and bower instead. Suggesting wontfix on this.

**Comment by dsaf** [comment]
@jstensved only for legacy code though (JS, CSS etc.) as far as I understand. .NET code will still be using NuGet. But yeah, can be closed I guess.
