### ISSUE TITLE
When ng-hide is set on on a wz-step, it still shows in the progress bar.

### ISSUE THREAD

**Issue by LucasKA** [mgonto/angular-wizard#62]
One of the best things about Angular form validation, is it's easy to make conditional form flow, since it won't attempt to validate a hidden form.

When adding ng-hide/ng-show to a wizard step, Angular Wizard should hide/show it's corresponding dot on the progress, which would make a much easier flow for creating wizards for say, differing user types and such.

**Comment by jacobscarter** [comment]
enable and disable steps is now a feature in the published version that will solve this issue
