### ISSUE TITLE
Wizard step validators added in canenter/canexit unaware of wz-previous or wz-next direction

### ISSUE THREAD

**Issue by vtytar** [mgonto/angular-wizard#74]
If you have some inputs on one of the steps that requires validation, it would most certainly be done via canexit callback. But canexit is called regardless of wz-next or wz-previous is pressed. 

The weird problem I faced in my application is that I cannot return to the previous step unless all fields are filled up correctly, which is not the desirable effect. It would be perfect if canexit callback was aware of direction we are jumping to and take a decision whether to run validation or not.

The way I found to work around this problem is simply by moving validation logic to canenter of the next page (this allows to use wz-previous without any constraints). Of course, I am not using steps indicator and the switching between the steps is done without jumping, straightforward next or previous. As you can see, this is not too much convenient.

Take a quick look if you want to fix it, it should be very easy: I guess a matter of few-lines fix.
Thanks.

**Comment by vtytar** [comment]
Tiny patch introduced in pull request#75.

**Comment by jacobscarter** [comment]
@vtytar I made the changes and am pushing it live so you can go back in steps without validating.  I am closing this ticket and your pull request, see my comments on the PR.

Thanks for pointing this out and your contributions!

**Comment by vtytar** [comment]
Thanks.
