### ISSUE TITLE
Next and Previous buttons have wrong tooltips

### ISSUE THREAD

**Issue by jvlasblom** [mgonto/angular-wizard#76]
The tooltip for the 'next' and 'previous' buttons shows the title of the current page, instead of the title for the next page or previous pages, respectively.

**Comment by jacobscarter** [comment]
@jvlasblom I'll look into this, I'll update you shortly.  Thanks for letting me know.

**Comment by geostima** [comment]
any updates on this issue yet?

**Comment by jacobscarter** [comment]
The buttons themselves dont have tooltips, the tooltip is only for the current step.  See #79, we will be adding a feature to disable tooltip but probably not to add ones to the buttons
