### ISSUE TITLE
how to validate all steps in edit-mode 

### ISSUE THREAD

**Issue by geminiyellow** [mgonto/angular-wizard#77]
hi all, 
now canexit/canenter were added, but if i use editMode, 
how can i validate all steps?
e.g. 
i have a wizard for regist. 
steps: 
account, infos, options.
infos has error.
but i can jump to options from account, and then press finish button.

can i get all steps validate infos? if invalid, can i jump back to the first invalid step?

**Comment by jacobscarter** [comment]
@geminiyellow Along with the addition of the canexit canenter attributes there was also the creation of a context object.  This object is accessible by all steps and is automatically passed in as an argument to your canexit canenter functions.  So for example:

*Your Controller*

    $scope.step1ExitValidation = function(){
        //logic for validation
        if(logicForValidation){
            WizardHandler.wizard().context.step1Valid = true;
            return true;
        } else {
            WizardHandler.wizard().context.step1Valid = false;
            return false;
        }
        
    }

    $scope.step3EnterValidation = function(contextObj){
        if(contextObj.step1Valid){
            return true;
        } else {
            return false;
        }
    }

*Your HTML*

    <wz-step canexit="step1ExitValidation></wz-step>
    <wz-step></wz-step>
    <wz-step canenter="step3EnterValidation"></wz-step>

Let me know if this was helpful.

Thanks.

**Comment by geminiyellow** [comment]
@jacobscarter thanks for your help sir, can i use the context like this?

HTML：

    <wizard on-finish="finishedWizard()"> 
        <wz-step title="Starting">
        </wz-step>
        <wz-step title="Continuing">
        </wz-step>
        <wz-step title="More steps">
        </wz-step>
    </wizard>

JS：

    $scope.finishedWizard = function(){
        var valid = _.every(stepnames, function(name){
            return WizardHandler.wizard().context[name].valid
        });

       if(valid) {
          // todo: end
       }else{
           WizardHandler.wizard().goto(firstInvalidStepTitle)
       }
    }

**Comment by jacobscarter** [comment]
@geminiyellow 

So I might need a little more context, for example you are looping through `stepnames`. Where is the value assigned to this? Is this the steps array from angular-wizard?

You are correctly creating the key/value pair in the context object, but I don't see you assigning a value to the `value` key of the context object.

So assuming you have created/defined the `stepnames` variable and that you are setting a value for  `context[name].valid` somewhere, then yes that should work.

**Comment by jacobscarter** [comment]
Let me know if this works for you and I will close the issue.
