### ISSUE TITLE
Each step shows title on hover

### ISSUE THREAD

**Issue by ttbarnes** [mgonto/angular-wizard#79]
Using the html title attribute causes this to show on a step, on hover. eg:

`<wz-step title="myStep">`

Instead, we could use `data-title`. It seems to work well:

`<wz-step data-title="myStep">`

**Comment by morfin** [comment]
Wonderful, the tooltip was starting to annoying me.

**Comment by bpbhat77** [comment]
+1

**Comment by kocsenc** [comment]
So is this closed then @ttbarnes ?

**Comment by ttbarnes** [comment]
@kocsenc No there needs to be a PR, personally haven't been able to yet.

**Comment by jacobscarter** [comment]
I will add an option to turn off tooltip on next release.

**Comment by jacobscarter** [comment]
hover no longer shows because we now use `wzTitle` you can always add a title attribute if you want hover effect
