### ISSUE TITLE
Additional custom data on step

### ISSUE THREAD

**Issue by sbiaudet** [mgonto/angular-wizard#82]
Is it possible to have an additional property wz-data for example to put custom data in step. It could be nice to customize wizard header with data from state.

**Comment by timmaybrown** [comment]
+1 for this enhancement.

**Comment by jacobscarter** [comment]
added and release, 0.6.1

**Comment by rsangiovanni** [comment]
Hi, just for understanding, in order to access to wz-data, we need to use $parent in this way?
```
<wz-step wz-title="step-i" wz-data="someData">
     <h2>Title:{{$parent.title}}</h2>
     <h2>Data name:{{$parent.someData.name}}</h2>
      ...
</wz-step>
```

**Comment by dev-thinks** [comment]
It is not clear how to set and get wz-data. would be great if someone help it out.
