### ISSUE TITLE
Wrap wz-step in another directive

### ISSUE THREAD

**Issue by MightyPixel** [mgonto/angular-wizard#84]
Hi how is it possible to do this:

    <wizard on-finish="finishedWizard()" current-step="currentStep" hide-indicators="true">
      <wz-step title="step1" canexit="validateStep">
       step body
      </wz-step>
    </wizard>

to:

    <wizard on-finish="finishedWizard()" current-step="currentStep" hide-indicators="true">
      <step-one></step-one>
    </wizard>

step-one directive contains the wz-step is it possible and how?

**Comment by jacobscarter** [comment]
@MightyPixel 

You could write your own directive to do this if you would like.  The trouble with doing something like this would be writing a directive to handle infinite number of steps. That is why we have wz-step.

Why is it that you want to do this?

**Comment by MightyPixel** [comment]
I'm doing a wizard that has different variations (every variation contains different steps) I want to abstract the boilerplate stuff like giving every step a title with simple directives that correspond to the steps. So constructing a wizard variation would mean to put n step directives in the wizard template.

Actually I made the step directives (the directives that contain the wz-step) and I have problems implementing deeplink functionality (navigating to specific step from url). I don't know when the wizard have finished initialising  and I end up trying to navigate to some step that isn't added to the $scope.steps.

Any ideas :)?

**Comment by jacobscarter** [comment]
Can you show some code to help me get some context
