### ISSUE TITLE
Add suport for async validations

### ISSUE THREAD

**Issue by RodrigoAxel** [mgonto/angular-wizard#90]
It would be VERY useful if the 'canexit' and 'canenter' methods accepted a promise, this way we would be able to make ajax calls for validation purposes.

**Comment by RodrigoAxel** [comment]
Nevermind, you can validate the form synchronously using the angular build-in form property '$valid' and '$pending'.

For example you can add this function to validate an step:

    $scope.validate = function () {

        //Only can change step if the form is valid and has no pending ajax requests
        return $scope.myForm.$valid && !$scope.myForm.$pending;
    };

For more information please read forms documentantion: 
https://docs.angularjs.org/guide/forms

NOTE: To use Angular's $asyncValidators you need angular version >= 1.3

**Comment by jacobscarter** [comment]
Thanks for the great ideas, I am going to work on implementing this

**Comment by jacobscarter** [comment]
@RyanDale thanks for the PR, I merged it and made the following changes in case you are interested:

Line 153 I moved it so canExitStep runs before canEnterStep

Line 188 and 211 I passed in `$scope.context` in as an argument, otherwise this context object was only available if you were using promises.

Thanks again!

**Comment by RyanDale** [comment]
@jacobscarter thanks for merging it in, good catch on both of those issues. The one thing I didn't do was update the documentation so I'm planning on doing that within the next few days.

**Comment by jacobscarter** [comment]
@RyanDale I updated the readme file yesterday, go ahead and give it a read and let me know if you think it should have more detail or if I left anything out
