### ISSUE TITLE
Supporting route-driven wizard steps

### ISSUE THREAD

**Issue by rpocklin** [mgonto/angular-wizard#93]
I've created a few wizards before in Angular.js, similar this one, but since this doesn't have routes integrated so when the user refreshes the page they will lose the context of which page their on :(

If it's out of scope for this directive that's cool, but I wanted to ask if this is in the plan at some point to see if you wanted to do it here rather than creating a separate directive.

To give you an idea, mine to date leverages **ui-router** and optionally use **local storage** or another pluggable implementation to keep the state of the form(s) between steps.

**Comment by jacobscarter** [comment]
@rpocklin would you be able to submit a Pull Request?

**Comment by rpocklin** [comment]
If I did, it would be a large PR and couple this library to **ui-router**.  If you're happy with that i'll fork it and have a go but only if it's probable to be accepted as a way forward.  Much of the view-switching logic will change.

With the angular-new-router being finalised, the decision becomes harder :)

**Comment by jacobscarter** [comment]
@rpocklin All good points, I think for now this might be a nice improvement for the future, perhaps when/if we re address this wizard for Angular 2.0

I will close the issue for now.

Thanks.
