### ISSUE TITLE
Validation Not Firing

### ISSUE THREAD

**Issue by Dog** [mgonto/angular-wizard#95]
I'm pretty new to Angular and I'm having trouble getting my validation functions to fire after reading through the documentation.

Here is my code on Plunker:
http://plnkr.co/edit/QR9mpXH67ErhUzAKmN4c?p=preview

I'm guessing its a scope issue?

**Comment by Dog** [comment]
I still don't know why this isn't working.

**Comment by jacobscarter** [comment]
Hey @Dog I will check out your Plunker tonight and get back to you

**Comment by jacobscarter** [comment]
@Dog I looked at your plunker and replaced your angular-wizard.js file in rawgit with the newest version from the repo and everything works.

Please update the dependency in your project and let me know if that fixes it.

Thanks

**Comment by Dog** [comment]
I found I was able to get it to work by pasting the url for the latest file on GitHub to rawgit, however when I tried to replace my link and script tags to the ones on the project description, the library didn't work. I'm not sure why that would happen.

**Comment by jacobscarter** [comment]
@mgonto do you need to re submit the recent versions of the project to jsDelivr?

**Comment by jacobscarter** [comment]
@Dog I just sent the updated files to jsDeliver, they should be up shortly.  The README.md file has been updated to reflect the new CDN URL.

Thanks.
